### ISSUE TITLE
Default compression also int16?

### ISSUE THREAD

**Issue by carlacodes** [kavli-ntnu/npx-compress#1]
Hi, do you know the default compression for the nidaq channels for this wrapper? Is it also in a default int16 format? 

e.g. like, on the mtscomp readme it states the default option of int16 compression. 
``
mtscomp data.bin -n 385 -s 30000 -d int16 [--set-default]
``

thanks!

**Comment by fralik** [comment]
Yes, I think that it is int16. See here: https://github.com/kavli-ntnu/npx-compress/blob/d7fdf2cb2b785832abeff01f95106c57788736d7/npxcompress/cli.py#L13C11-L13C11

**Comment by carlacodes** [comment]
Thank you, closing this thread now.
